#fos_user_rest:
#    type: rest
#    resource: AppBundle\Controller\FosUserRestController


api_login_check:
    path: /login_check

routing_rest:
    resource: routing_rest.yml

  
question:
    resource: "@AppBundle/Controller/QuestionController.php"
    type:     annotation     

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"